### ISSUE TITLE
Analysis of Gradebooks -- In scope?

### ISSUE THREAD

**Issue by daranzolin** [jrosen48/data-science-in-education#9]
It might be useful to include a section on EDA within the context of gradebooks. I suspect thousands of teachers and department chairs have exported a gradebook, opened the spreadsheet, and wondered what to do next. I myself have wondered what to look for when combing through summative and formative assessments. 

Please ignore the vulgarity of the code, but [I ventured a small tutorial for the Michigan Virtual Learning Research Institute (MVLRI) here.](https://mvlri.org/blog/gradebook-analysis-with-r-part-ii/) I would be interested to read a smarter person's take on something like this.

**Comment by kierisi** [comment]
Gradebooks are probably one of the biggest standardized data sources that a teacher uses, regardless of discipline, location, background, etc. In fact, gradebooks/trackers/etc. might be one of the best "touchstone" data pieces used as an example throughout the book - from import to wrangling and analysis and even prediction.

**Comment by jkaupp** [comment]
+1 to what @kierisi  said above, and this entire issue.  While it's the most common piece for instructors to use, there is one of two thing that happen (speaking from dealing with Engineering Faculty in Higher Ed).

1.  They make a histogram of midterm and final grades, look at the distribution and are done.
2.  They do what @daranzolin suggests.

These are people with advanced training in statistics and analysis and minimal training in education.  The hurdle for them is actually connecting the data back to the students, and using EDA and techniques that highlight learners within a cohort instead of hiding them.  I step in by showing them easy things to do with exports from their gradebook (actually, there's a Shiny app idea for me later...) and the associated data.  My landmark example for them is making a parallel coordinates chart using their assessments in sequence, and then illustrating how you can use simple clustering analysis to identify patterns.  

My point is having a section on EDA is good, but it should move beyond the typical cohort analysis that is done on the backs of histograms and scatterplots.  This section would naturally lead someone into the areas of learning analytics and educational data mining.

**Comment by daranzolin** [comment]
@kierisi @jkaupp do either of you know of another sample gradebook analysis? Perhaps resembling what you envisage for the book?

**Comment by restrellado** [comment]
Thank you for starting this issue! Can we anonymize an actual gradebook export and each take a crack at doing some EDA on it? Might be fun to share out and see how we all tackled it. Then we can extract some good practices and write it up for the book. 

By the way @daranzolin as a fellow Californian I'm totally interested in your CDE package!

**Comment by daranzolin** [comment]
@restrellado Hey thanks! I need to update it--I think they've released the 16-17 data since I created the package. 

My last foray into gradebooks was an attempt to identify "busy work", which we suspected littered our curriculum. A metric I considered was the R^2 between the assignment and a formative assessment, such as a mid-term or final exam. For example, would a low R^2 imply busy work? Crude, but suggestive.

**Comment by jsonbecker** [comment]
Are there any standardized data formats for grade information? I haven't worked much across site with non-course level grading, but I'm assuming there are some common formats for standards-based grading and traditional grading beyond "spreadsheet with kids in rows and grades for assessments in columns".

FWIW, grade books in the classic sense seem like a great tool to learn about "long" versus "wide" data, moving between those formats, and the benefits/tradeoffs of each.

**Comment by jkaupp** [comment]
I'd venture to say that 90% of LMS gradebooks are just that, and would be a potential in-context data set to illustrate long v wide.

@daranzolin  IMO, relevance goes hand in hand with curriculum design and alignment rather than performance.  If you're ignoring constructive alignment then I'd label it 'busy work', but if the assessment is timely, purposeful and meaningful then it is hardly 'busy work'.  This is something that you'll rarely see in grades, and something that is intimately tied to a bucket of external factors.  Instead I see gradebooks as the gateway to showing instructors that moving beyond the histogram can tell you a great deal about learners in your classroom, help inform and improve your teaching, and start them on the road of being a reflective teacher.

**Comment by kierisi** [comment]
seconding the format of gradebooks - it's been my experience as a HS teacher that it's up to individuals to create their own gradebooks, which almost always involved wide data in Excel.

some schools do purchase software for grading, and each program has varying levels of access to the data - the ones I've used will show you different dashboards, but if you want to work with the data yourself, you need to have stored it in an Excel file.

I don't have access to anonymized student data, but can ask around to some teacher friends!

**Comment by restrellado** [comment]
I started a [script for us to make a fake wide format gradebook dataset](https://github.com/restrellado/sample_gradebook). This is just a start. Please feel free to do whatever you need to make it more authentic. I'll add everyone here as collaborators.
